# Generated by Django 4.1 on 2022-08-17 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weather", "0002_alter_city_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="city",
            name="name",
            field=models.CharField(max_length=30),
        ),
    ]
